
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages

server:
  port: 8080
  managementPort: 8081

accessToken:
  validityInSeconds: 86400

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}
  template:
    invite: ${GOV_NOTIFY_INVITE_TEMPLATE_ID:template}
    reset: ${GOV_NOTIFY_RESET_TEMPLATE_ID:template}
    resetSuccessful: ${GOV_NOTIFY_RESET_SUCCESSFUL_TEMPLATE_ID:template}

invite:
  url: ${INVITE_SIGNUP_URL:http://localhost:8080/signup/%s}
  validityInSeconds: 86400

reset:
  url: ${RESET_URL:http://localhost:8080/reset/%s}
  validityInSeconds: 86400

accountValidation:
  passwordPattern: ${PASSWORD_PATTERN:(?!([a-zA-Z]*|[a-z\d]*|[^A-Z\d]*|[A-Z\d]*|[^a-z\d]*|[^a-zA-Z]*)$).{8,}}

---

spring:
  profiles: production
  thymeleaf:
    cache: true
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/oauth2?user=root&password=secret&useSSL=false}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true


