
server:
  port: 8080
  managementPort: 8081

accessToken:
  validityInSeconds: 86400

govNotify:
  key: ${GOV_NOTIFY_API_KEY_TEST}
  template: ${GOV_NOTIFY_TEMPLATE_ID}

invite:
  validityInSeconds: 86400
---

spring:
  profiles: production
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/oauth2?user=root&password=secret&useSSL=false}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true


