spring:
  data:
    redis:
      repositories:
        enabled: false
  session:
    store-type: none
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:3600}
  port: 8080
  managementPort: 8085

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    org.apache.http: WARN

accessToken:
  jwtKey: ${jwt_key}
  validityInSeconds: ${ACCESS_TOKEN_VALIDITY:86400}

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}
  template:
    invite: ${GOV_NOTIFY_INVITE_TEMPLATE_ID:7ef048a3-5c82-40fd-be4c-a238ce328fea}
    reset: ${GOV_NOTIFY_RESET_TEMPLATE_ID:d29b056c-349b-42fc-a453-920cfb58a906}
    resetSuccessful: ${GOV_NOTIFY_RESET_SUCCESSFUL_TEMPLATE_ID:994fb6d4-a57a-49f2-baee-b0c6f6060b63}
    passwordUpdate: ${GOV_NOTIFY_PASSWORD_UPDATE_TEMPLATE_ID:13c2b9ac-4ad0-449f-b43b-57c04fc88b1d}
    emailUpdate: ${GOV_NOTIFY_EMAIL_UPDATE_TEMPLATE_ID:f4c2ece1-5159-4736-92cb-4fe0df719308}

invite:
  url: ${INVITE_SIGNUP_URL:http://localhost:8080/signup/%s}
  validityInSeconds: ${INVITE_VALIDITY:259200}
  durationAfterReRegAllowedInSeconds: ${DURATION_AFTER_REREG_ALLOWED_SECONDS:86400}
  whitelist:
    domains: ${WHITELISTED_DOMAINS:example.com, domain.com, gov.uk}

reset:
  url: ${RESET_URL:http://localhost:8080/reset/%s}
  validityInSeconds: ${RESET_VALIDITY:86400}

emailUpdate:
  urlFormat: "${lpg.identity}/account/email/verify/%s?redirect=true"

accountValidation:
  passwordPattern: ${PASSWORD_PATTERN:(?!([a-zA-Z]*|[a-z\d]*|[^A-Z\d]*|[A-Z\d]*|[^a-z\d]*|[^a-zA-Z]*)$).{8,}}

#AuthenticationFailureListener in current Spring version is firing twice so need to increase maxAttempt value till fixed
#https://github:com/spring-projects/spring-security/issues/6281:
account:
  lockout:
    maxAttempt: 12

maintenancePage:
  enabled: ${MAINTENANCE_PAGE_ENABLED:false}
  content: ${MAINTENANCE_PAGE_CONTENT:The learning website is undergoing scheduled maintenance. It will be unavailable between the hours of 7pm to 9pm on Wednesday 3rd February 2021.}

lpg:
  uiUrl: ${LPG_UI_URL:http://localhost:3001}
  identity: ${OAUTH_SERVICE_URL:http://localhost:8080}

registry:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  agencyTokensFormat: "${registry.serviceUrl}/agencyTokens?domain=%s&token=%s&code=%s"
  agencyTokensByDomainFormat: "${registry.serviceUrl}/agencyTokens?domain=%s"
  agencyTokensByDomainAndOrganisationFormat: "${registry.serviceUrl}/agencyTokens?domain=%s&code=%s"
  organisationalUnitsFlatUrl: "${registry.serviceUrl}/organisationalUnits/flat"
---

spring:
  profiles: test, production
  thymeleaf:
    cache: true
    check-template: true
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/identity?user=root&password=password&useSSL=false}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    password: ${REDIS_PASSWORD:redispassword}
    port: ${REDIS_PORT:6379}
  session:
    redis:
      namespace: spring:session
      flush-mode: on-save
    store-type: redis
